CREATE DATABASE IF NOT EXISTS classmates_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE classmates_db;

CREATE TABLE IF NOT EXISTS birthdays (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  dob DATE NOT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
